name: Deploy to github pages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          apt-get update -q && apt-get install -y -q yarnpkg
          (cd frontend; PUBLIC_URL="https://anuejn.github.io/fpl.zip/" yarnpkg build)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./frontend/dist